Apexal/late

server/controllers/home.js
views/template.pug

Fixes issue #24 
- View template uses the 'title' variable set in each route controller.

Template page title takes from 'title' state variable

---

config/default.json
db/index.js
package.json
server/index.js

Closes issue #8 
- Use Mongoose to connect to MongoDB
- Config files used to connect to DB
- Schemas are in `/db/schemas/`

MongoDB Setup

---

db/schemas/assignment.js
db/schemas/block.js
db/schemas/student.js
package.json

Fixes issue #8
- implement schemas for Student, Assignment, and Block

MongoDB Setup with Schemas

---

package.json
server/auth.js
server/index.js
server/routes/home.js
server/routes/index.js
views/includes/_header.pug

Fixes issue #31 
- implement CAS auth
- works outside RPI servers contrary to jfinke

CAS Auth (safe)

---

db/index.js
index.js
package.json
server/auth.js
server/index.js
server/logger.js

Fixes issue #38 
- implement winston for logging
- log to console when not in production mode
- always log to files in ./logs

Feature logging

---

server/auth.js
server/index.js
views/includes/_flash.pug
views/template.pug

Fixes issue #39 
- flash handled in session
- flash view input into template

Feature flash messages

---

db/schemas/student.js
package.json
server/auth.js
server/cms_api.js
server/controllers/setup.js
server/index.js
server/routes/index.js
server/routes/setup.js
server/scraping.js
server/yacs_api.js
views/error.pug
views/includes/_header.pug
views/setup/course_schedule.pug
views/setup/personal_info.pug
views/setup/setup_template.pug
views/template.pug

Closes issue #39 #37 #12 
- SIS scraping for CRNs given RIN and PIN
- YACS API to get section info from CRNs
- automated setup routes

YACS API, SIS Scraping, User Setup

---

views/home/about.pug
views/includes/_footer.pug

About page start

---

server/yacs_api.js

Fix YACS uri bug

---

client/sass/routes/_assignments.scss
db/schemas/student.js
server/auth.js
server/controllers/assignments.js
server/controllers/setup.js
server/routes/assignments.js
server/routes/home.js
views/assignments/list.pug
views/assignments/new.pug

Fixes issue #55 
- `course_schedule` -> `semester_schedules` in schema
- `current_schedule` student virtual getter and setter
- pseudo-course object for "Other" (closes #54)

Feature keep schedules

---

db/schemas/student.js
package.json
server/controllers/api/integrations.js
server/discord.js
server/index.js
server/routes/api/integrations.js
src/components/profile/DiscordSetup.vue
src/components/profile/EmailSetup.vue
src/components/profile/SMSSetup.vue
src/views/profile/IntegrationsSetup.vue

Merge Integrations

---

db/schemas/student.js
package.json
server/controllers/api/integrations.js
server/discord.js
server/index.js
server/routes/api/index.js
server/routes/api/integrations.js
server/sms.js
src/components/profile/DiscordSetup.vue
src/components/profile/EmailSetup.vue
src/components/profile/SMSSetup.vue
src/views/profile/IntegrationsSetup.vue

Feature integrations

---

package.json
server/modules/google.js
server/routes.js

With this, students will be able to connect their Google accounts so that LATE can access and edit their calendars.

Google Authentication

---

src/components/TheFooter.vue
src/components/TheHeader.vue
src/components/profile/SetupIntegrationsDiscord.vue
src/components/profile/SetupIntegrationsEmail.vue
src/components/profile/SetupIntegrationsSMS.vue
src/views/profile/ProfileSetupCourseSchedule.vue
src/views/profile/ProfileSetupPersonalInfo.vue
src/views/profile/ProfileSetupUnavailability.vue

Fixes issue flow between setup pages was not correctly done. Otherwise changes in footer for simplicity as well in the header.
-
-
-

Last minute ui changes

---

server/api/assignments/assignments.model.js
server/api/blocks/blocks.controller.js
server/api/blocks/index.js
server/api/exams/exams.controller.js
server/api/exams/exams.model.js
src/components/assignments/overview/AssignmentOverviewTabs.vue
src/components/assignments/overview/tabs/AssignmentOverviewabsWorkSchedule.vue
src/components/sidebar/TheSidebar.vue
src/store/modules/work.js
src/views/TheDashboard.vue
src/views/assignments/AssignmentsOverview.vue
src/views/exams/ExamsOverview.vue

Feature google

---

src/App.vue
src/assets/bulma.scss
src/components/TheHeader.vue
src/components/TimeInput.vue
src/components/sidebar/TheSidebar.vue
src/views/profile/ProfileSetupUnavailability.vue

Fixes issue #185 
- make sidebar fixed on non-mobile
- scroll smoothly to proper location
- auto-resize horizontally on window resize

Sidebar Fixed to Screen

---

src/components/TimeInput.vue
src/views/assignments/Assignments.vue
src/views/profile/ProfileSetupUnavailability.vue

Fixes issue #190 
- use `localStorage` to track status of show completed assignments

Persist show completed on Assignments page

---

src/views/assignments/AssignmentsOverview.vue

Breaks words on Assignments page (closes #197)

---

server/api/students/students.controller.js
src/components/TimeInput.vue
src/views/profile/ProfileSetupUnavailability.vue

Fixes issue #188 
- create new student on `/loginas` route if in dev mode

Create new dev users

---

src/components/sidebar/SidebarPressingAssignments.vue
src/components/sidebar/SidebarSchedule.vue
src/components/sidebar/SidebarTodoList.vue
src/components/sidebar/SidebarUpcomingExamsList.vue
src/components/sidebar/TheSidebar.vue

Fixes issue #49
- Enable vertical scrollbar on sidebar content when the content takes up more than a certain amount of vertical space.
- Disable the horizontal scrollbar in all cases.

49 sidebar overflow

---

src/components/CoursePeriodsTable.vue
src/components/courses/CourseModal.vue
src/components/courses/CourseModalLinks.vue
src/components/courses/CourseModalSchedule.vue
src/components/courses/CourseModalUpcoming.vue
src/views/assignments/AssignmentsOverview.vue
src/views/assignments/AssignmentsPastList.vue
src/views/assignments/AssignmentsUpcoming.vue

- Course modal now has 3 tabs: upcoming assessments, course schedule, and course links

Improved Course Modal

---

src/components/AssessmentOverviewWorkSchedule.vue
src/components/assignments/overview/AssignmentOverviewActionButtons.vue
src/views/assignments/Assignments.vue
src/views/assignments/AssignmentsOverview.vue
src/views/exams/Exams.vue

Remove export btn

---

src/components/AssessmentOverviewWorkSchedule.vue
src/components/assignments/overview/AssignmentOverviewActionButtons.vue
src/views/assignments/AssignmentsOverview.vue

Fixes issue #244 
- this allows full editing capabilities for passed assignments, which removes a previous assumption that remove was the only capability desired for past assignments.

Edit overdue

---

src/components/TheHeader.vue

Header was very tall and this helps maximize space

Narrows header spacing

---

src/views/TheHomePage.vue

Add SIS man

---

package.json
server/api/integrations/index.js
server/api/integrations/integrations.controller.js
server/api/students/students.model.js
server/routes.js
src/assets/bulma.scss
src/views/components/profile/SetupIntegrationsDiscord.vue
src/views/profile/ProfileSetupIntegrations.vue

Fixes issue #275 
- allow users to connect to Discord officially
- save their user ID to database
- add them to the LATE server when connected with the `BETA Tester` role and nickname of their LATE display name

Discord Authentication

---

src/store/modules/auth.js
src/store/modules/schedule.js
src/store/modules/work.js
src/views/components/profile/ProfileCourse.vue
src/views/profile/ProfileSetupCourseSchedule.vue

Fixes issue #268 
- Add a 'hidden' property to courses
- Hidden courses are not shown in filters and modals
- Hidden courses are still shown in calendars and the sidebar

Hidden courses

---

server/api/announcements/announcements.controller.js
server/api/announcements/announcements.model.js
server/api/announcements/index.js
server/api/index.js
src/App.vue
src/store/index.js
src/store/modules/announcements.js
src/views/components/TheHeader.vue
src/views/components/announcements/AnnouncementsModal.vue

Fixes issue #294 
- check it out

Announcements

---

server/api/assignments/assignments.controller.js
server/api/assignments/assignments.model.js
server/api/assignments/index.js
server/api/blocks/blocks.controller.js
server/api/exams/exams.controller.js
server/api/students/students.model.js
server/api/unavailabilities/unavailabilities.controller.js
src/App.vue
src/store/modules/assessments.js
src/store/modules/unavailability.js
src/views/assessments/AssessmentsCalendar.vue
src/views/assessments/AssessmentsOverviewPage.vue
src/views/components/assessments/AssessmentOverviewActionButtons.vue
src/views/components/assessments/AssessmentOverviewComments.vue
src/views/components/assessments/AssessmentOverviewDescription.vue
src/views/components/assessments/AssessmentOverviewStats.vue
src/views/components/assessments/AssessmentOverviewTitle.vue
src/views/components/assessments/AssessmentOverviewWorkSchedule.vue
src/views/components/assessments/AssessmentsTable.vue
src/views/components/assessments/upcoming/AssessmentPanelBlock.vue
src/views/components/assignments/AssignmentsModalEdit.vue
src/views/components/assignments/overview/AssignmentOverviewTabs.vue
src/views/components/assignments/overview/AssignmentOverviewTabsSharedInfo.vue
src/views/components/courses/CourseModalUpcoming.vue
src/views/components/dashboard/DashboardCalendarSelectModal.vue
src/views/components/exams/ExamsModalEdit.vue
src/views/components/exams/overview/ExamOverviewStudyPlan.vue
src/views/components/exams/overview/ExamOverviewTabs.vue
src/views/components/sidebar/SidebarPressingAssessments.vue
src/views/dashboard/DashboardCalendar.vue

Fixes issue #343 
Assignments can now be shared with other LATE users. Shared assignments allow collaborators to comment and schedule work blocks for everyone on the assignment. These show up in all collaborators' schedules, calendars, etc. and are clearly marked as shared. Only the assignment owner can edit details about the assignment and can toggle sharing entirely and add/remove collaborators whenever.
With this PR the basic functionality is done but there is more work to do like automatically updating collaborators states if they are online when another collaborator makes a change to the assignment.

Assignment Collaboration

---

src/modules/haikus.js

Wrote some more haikus for the 404 page

More Haikus
